### ISSUE TITLE
Can't install stuff

### ISSUE THREAD

**Issue by BadPythonCoder** [PC-trollbox/DuckCloud#24]
Whenever i try to install anything, it times out. I also tried all the other distro's excep cent os.
Ping isn't installed by default so i couldnt test other sites.

btw i 100% enabled network.

![afbeelding](https://github.com/PC-trollbox/DuckCloud/assets/66245823/c7e396ad-4037-4ff0-841a-a2fb8be5b0ce)

**Comment by PC-trollbox** [comment]
is this on the official instance? I've restarted the official instance and it started to work

**Comment by BadPythonCoder** [comment]
It was on the official instance

**Comment by BadPythonCoder** [comment]
Ok it works normally, i don't know what happened but it is no longer an issue
